language: java
env:
- PLAY_VERSION=2.2.3
before_script:
- wget http://downloads.typesafe.com/play/${PLAY_VERSION}/play-${PLAY_VERSION}.zip
- unzip -q play-${PLAY_VERSION}.zip
script: play-${PLAY_VERSION}/play test
deploy:
  provider: heroku
  app: bagelnet-todolist3
  api_key: oBHEwB8lYNHVeiAY4EYEDxDmzvx5jpejkB4rGx9XAshasUKmINU7ewfbtlu+PxZtkUneWgVpUcIaBZeoThxYiaC97iiZkZJO6KcyV1Yfs3goReRk49wf8wLE9ZBIVOFf0pOrVtNqFcCGORQAOc4Y/L0QVPg8MJu8MIulzu9YHys=
