language: java
env:
- PLAY_VERSION=2.2.3
before_script:
- wget http://downloads.typesafe.com/play/${PLAY_VERSION}/play-${PLAY_VERSION}.zip
- unzip -q play-${PLAY_VERSION}.zip
script: play-${PLAY_VERSION}/play test
deploy:
  provider: heroku
  app: bagelnet-todolist
  api_key:
    secure: WKlotArlNllb6j/hxYm6gMg6TFhoUPIB5cimc9/KWRcUy/FxPbWz4VyxlOXCazWFU+6fGPviTSOPP2gtJveAVEJzd7PDEIb5Zn+0PkBwgCTNZIglo4pQs9CmIr7hdnbimGD+4lANc8676/rtCSqsAZvbWHND6f1hbJs7J0L7j+I=
